package com.ablodich.smis.diagnostictaskrouterservice.entity.enumerate;

public enum DiagnosisTaskState {
    STARTED,
    APPOINTMENT_VALIDATION_COMPLETED,
    DIAGNOSIS_PENDING,
    DIAGNOSIS_COMPLETED,
    APPOINTMENT_VALIDATION_COMPLETED_AND_DIAGNOSIS_PENDING,
    DIAGNOSIS_COMPLETED_AND_APPOINTMENT_VALIDATION_PENDING,
    APPOINTMENT_VALIDATION_AND_DIAGNOSIS_PENDING,
    APPOINTMENT_VALIDATION_AND_DIAGNOSIS_COMPLETED,
    APPOINTMENT_LINKING_PENDING,
    APPOINTMENT_LINKING_COMPLETED,
    COMPLETED,
    CANCELLED,
    ERROR
}
