BOOTSTRAP_SERVERS: localhost:9092

SERVER_PORT: 8084

JDBC_USERNAME: postgres
JDBC_PASSWORD: postgres
JDBC_URL: jdbc:postgresql://localhost:5432/postgres?currentSchema=ml-brain-mri-classification-service
